### ISSUE TITLE
Validating Certificate

### ISSUE THREAD

**Issue by pierbiag** [disig/TimeStampClient#2]
Hello and thanks for the client.

I'm writing to ask how you can validate the asics archive or the token once after creating it on windows.

In particular I use www.freetsa.org.

Thank you in advance,
Pier

**Comment by jariq** [comment]
ASiC-S container can be validated for example by our online service [ZEP.DISIG.SK](https://zep.disig.sk/Portal/en). However TSA at freetsa.org does not seem to be qualified service operated under the terms of eIDAS regulation so the validation result for its certificate will most likely be "indeterminate".
