### ISSUE TITLE
Verification of tst with openssl is failing

### ISSUE THREAD

**Issue by steamonimo** [disig/TimeStampClient#6]
I am using your client gui to create the tst file. The timestamping authority I am using is "https://freetsa.org/tsr". The tst file is successfully created.

However the verification with openssl is showing the following error:

openssl ts -verify -data file.exe -in file.exe.tst -CAfile freetsa.pem -untrusted freetsa2.pem

Verification: FAILED
13376:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:crypto\asn1\tasn_dec.c:1130:
13376:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:290:Type=TS_STATUS_INFO
13376:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:crypto\asn1\tasn_dec.c:627:Field=status_info, Type=TS_RESP

The version of openssl is OpenSSL 1.1.1d  10 Sep 2019.

I can reproduce the problem with the timestamping authorities "https://freetsa.org/tsr" and "https://www.safestamper.com/tsa".

**Comment by kleinmrk** [comment]
@steamonimo, the application saves time-stamp token, not the time-stamp response. You need to add [`-token_in`](https://www.openssl.org/docs/man1.1.1/man1/openssl-ts.html) to the verification command.

```
openssl ts -verify -data file.exe -in file.exe.tst -token_in -CAfile freetsa.pem -untrusted freetsa2.pem
```

**Comment by steamonimo** [comment]
Thanks, now the verification is working. Wouldn't it be helpful to have a choice between time-stamp response or token as a parameter to the call perhaps? In my case I am switching from openssl and thus have time-stamp responses. To continue this with your client it would be helpful to save the response.
